apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-track-config
  namespace: travel-track
  labels:
    app: travel-track-api
data:
  # Configuración de la aplicación
  NODE_ENV: "production"
  PORT: "3000"
  APP_VERSION: "1.0.0"
  APP_NAME: "travel-track-api"
  LOG_LEVEL: "info"
